plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

dependencies {
    implementation project(":core")
    api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}

// Run task
task run(dependsOn: classes, type: JavaExec) {
    mainClass = 'com.staticgame.desktop.DesktopLauncher'
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = rootProject.file('assets')
    ignoreExitValue = true
    if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
        jvmArgs "-XstartOnFirstThread"
    }
}

// Fat JAR task
task dist(type: Jar) {
    dependsOn(':core:jar')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes 'Main-Class': 'com.staticgame.desktop.DesktopLauncher'
    }

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    from files("../assets") // <--- ADD THIS EXACT LINE
    with jar
}